version: "3.9"
services:
  app:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_DB: your_database
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
