services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_management_system
      MYSQL_USER: user
      MYSQL_PASSWORD: "W7301@jqir#"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
