name: Library Management System CI/CD

on:
  push:
    branches: [ cisetup ]
  pull_request:
    branches: [ cisetup ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: W7301@jqir#
          MYSQL_DATABASE: library_management_system
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up database schema
      run: |
        mysql -h127.0.0.1 -uroot -pW7301@jqir# library_management_system < schema.sql


    
    - name: Run tests
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: root
        MYSQL_PASSWORD: W7301@jqir#
        MYSQL_DB: library_management_system
      run: |
        pytest tests/test1_app.py
        pytest tests
        pytest run_tests.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to production
      # Add your deployment steps here
      run: |
        echo "Deploying to production"
        # Add actual deployment commands
